name: math-prelude
version: '0.2.0.0'
synopsis: A better prelude for maths.
description: I have introduced a new hierarchy of typeclasses for arithmetic, aligned
  with mathematical convention. This both gets rid of the strange quirks of Haskell's
  standard numerical classes, but also allows for richer and expressive mathematical
  constructions to extend from it.
category: Math
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: GPL-3
homepage: https://github.com/RossOgilvie/math-prelude
other-extensions:
- RebindableSyntax
- UnicodeSyntax
- NoImplicitPrelude
- CPP
- OverloadedStrings
ghc-options:
- -O2
- -Wall
- -fwarn-tabs
dependencies:
- base ==4.12.0.0
- system-filepath >=0.4 && <0.5
- text >=1.2 && <1.3
- safe >=0.3 && <0.4
library:
  exposed-modules:
  - MathPrelude
  - MathPrelude.Classes.Approximate
  - MathPrelude.Classes.Transcendental
  - MathPrelude.Classes.Integral
  - MathPrelude.Classes.Group
  - MathPrelude.Classes.Ring
  - MathPrelude.Classes.Rational
  - MathPrelude.Classes.Field
  - MathPrelude.Classes.EuclideanDomain
  - MathPrelude.Classes.Real
  - MathPrelude.Classes.VectorSpace
  - MathPrelude.Classes.Norm
  - MathPrelude.Constructions.Ratio
  - MathPrelude.Constructions.Complex
  - MathPrelude.Constructions.Polynomial
  other-modules:
  - MathPrelude.Prelude.CorePrelude
  - MathPrelude.Prelude.Logic
  - MathPrelude.Prelude.IntegralLists
  - MathPrelude.Prelude.NamedNumbers
