name: math-calculus
version: '0.1.0.0'
category: Math
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: GPL-3
other-extensions:
- RebindableSyntax
- UnicodeSyntax
- FlexibleInstances
- MultiParamTypeClasses
dependencies:
- base ==4.12.0.0
- math-prelude
- math-linear
library:
  exposed-modules:
  - MathPrelude.Calculus.Derivation
  - MathPrelude.Calculus.NewtonsMethod
  - MathPrelude.Calculus.Convergence
  - MathPrelude.Calculus.Integration
  - MathPrelude.Calculus.VectorCalc
