flags: {}
packages:
- math-prelude/
- math-linear/
- math-calculus/
- math-special-functions/
- math-extras/
- math-geometry/
- math-graphics/
extra-deps:
- easyplot-1.0
- ReadArgs-1.2.3
resolver: lts-13.3
