name: math-linear
version: '0.1.0.0'
category: Math
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: GPL-3
other-extensions:
- RebindableSyntax
- UnicodeSyntax
- OverloadedStrings
- DataKinds
- FlexibleInstances
- KindSignatures
- MultiParamTypeClasses
- PolyKinds
- TypeFamilies
- TypeOperators
- ScopedTypeVariables
- FlexibleContexts
- UndecidableInstances
dependencies:
- base ==4.12.0.0
- math-prelude
- lens
library:
  exposed-modules:
  - MathPrelude.Constructions.Matrix
  - MathPrelude.Constructions.Vector
