name: math-geometry
version: '0.1.0.0'
category: Math
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: GPL-3
other-extensions:
- RebindableSyntax
- UnicodeSyntax
- OverloadedStrings
- DataKinds
- FlexibleInstances
- KindSignatures
- MultiParamTypeClasses
- PolyKinds
- TypeFamilies
- TypeOperators
- ScopedTypeVariables
- FlexibleContexts
- UndecidableInstances
- ViewPatterns
dependencies:
- base ==4.12.0.0
- math-prelude >=0.2 && <0.3
- math-linear >=0.1 && <0.2
- lens
library:
  exposed-modules:
  - MathPrelude.Constructions.Sphere3
  - MathPrelude.Constructions.Sphere1
  - MathPrelude.Constructions.Disc2
  - MathPrelude.Constructions.Projective
