name: math-special-functions
version: '0.1.0.0'
category: Math
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: GPL-3
library:
  other-extensions:
  - BangPatterns
  - RebindableSyntax
  - UnicodeSyntax
  ghc-options: -O2
  exposed-modules:
  - MathPrelude.SpecialFunctions.EllipticFunctions
  - MathPrelude.SpecialFunctions.SpecialFunc
  - MathPrelude.SpecialFunctions.Primes
  - MathPrelude.SpecialFunctions.Combinatorics
  dependencies:
  - base ==4.12.0.0
  - math-prelude >=0.2 && <0.3
  - math-calculus >=0.1 && <0.2
  - primes
benchmarks:
  bench-ellipticfunctions:
    main: EllipticFunctionsBench.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -rtsopts
    - -threaded
    - ! '"-with-rtsopts=-N -p -s -h -i0.1"'
    dependencies:
    - base
    - criterion
    - math-prelude
    - math-special-functions
