name: math-graphics
version: '0.1.0.0'
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: UnspecifiedLicense
other-extensions:
- RebindableSyntax
- UnicodeSyntax
dependencies:
- base ==4.12.0.0
- math-prelude >=0.2 && <0.3
- easyplot ==1.0
library:
  exposed-modules:
  - MathPrelude.Graphics.ThreeDViewer
  - MathPrelude.Graphics.TwoDViewer
